jobs:
  include:
      - stage: server
        name: "Server (Express)"
        language: node_js
        node_js: "8"
        before_script:
          - npm install
        script:
          - npm test
      - stage: client
        name: "Client (Angular)"
        language: node_js
        node_js: "8"
        before_script:
          - cd client
          - npm install
        script:
          - ng test