jobs:
  include:
      - stage: server
        name: "Server (Express)"
        language: node_js
        node_js: "8"
        before_script:
          - "npm install"
        script:
          - "npm test"
      - stage: client
        name: "Client (Angular)"
        sudo: required
        addons:
              chrome: stable
        language: node_js
        node_js: "8"
        before_script:
          - "export DISPLAY=:99.0"
          - "sh -e /etc/init.d/xvfb start"
          - "cd client"
          - "npm install"
        script:
          - "ng test"