jobs:
  include:
      - stage: "Server"
        language: node_js
        node_js: 8,
        before_script:
          - npm install
      script:
        - npm test
      - stage: "Client"
        language: node_js
        node_js: 8
        before_script:
          - cd client
          - npm install
        script:
          - ng test